import { type Category, type StackItem } from './stack-card';

export const stacks: StackItem[] = [
  // backend
  {
    name: 'Laravel',
    icon: '/icons/laravel.svg',
    level: 'Expert',
    category: 'backend',
    hasStar: true,
  },
  {
    name: 'Filament',
    icon: '/icons/filament.svg',
    level: 'Expert',
    category: 'backend',
    hasStar: false,
  },
  {
    name: 'PHP',
    icon: '/icons/php.svg',
    level: 'Expert',
    category: 'backend',
    hasStar: false,
  },
  {
    name: 'Wordpress',
    icon: '/icons/wordpress.svg',
    level: 'Expert',
    category: 'backend',
    hasStar: false,
  },
  {
    name: 'Node.js',
    icon: '/icons/node.js.svg',
    level: 'Advanced',
    category: 'backend',
    hasStar: false,
  },
  // frontend
  {
    name: 'React',
    icon: '/icons/react.svg',
    level: 'Expert',
    category: 'frontend',
    hasStar: true,
  },
  {
    name: 'Typescript',
    icon: '/icons/typescript.svg',
    level: 'Expert',
    category: 'frontend',
    hasStar: false,
  },
  {
    name: 'Livewire',
    icon: '/icons/livewire.svg',
    level: 'Expert',
    category: 'frontend',
    hasStar: false,
  },
  {
    name: 'Alpine.js',
    icon: '/icons/alpine.js.svg',
    level: 'Expert',
    category: 'frontend',
    hasStar: false,
  },
  {
    name: 'Vue.js',
    icon: '/icons/vue.js.svg',
    level: 'Intermediate',
    category: 'frontend',
    hasStar: false,
  },
  {
    name: 'Tailwind CSS',
    icon: '/icons/tailwindcss.svg',
    level: 'Expert',
    category: 'frontend',
    hasStar: false,
  },
  // libraries
  {
    name: 'Shadcn UI',
    icon: '/icons/shadcn.svg',
    level: 'Expert',
    category: 'library',
    hasStar: true,
  },
  {
    name: 'Bootstrap',
    icon: '/icons/bootstrap.svg',
    level: 'Expert',
    category: 'library',
    hasStar: false,
  },
  {
    name: 'Pest',
    icon: '/icons/pest.svg',
    level: 'Expert',
    category: 'library',
    hasStar: false,
  },
  {
    name: 'NativePHP',
    icon: '/icons/nativephp.svg',
    level: 'Intermediate',
    category: 'library',
    hasStar: false,
  },
  // databases
  {
    name: 'MySQL',
    icon: '/icons/mysql.svg',
    level: 'Expert',
    category: 'database',
    hasStar: true,
  },
  {
    name: 'SQLite',
    icon: '/icons/sqlite.svg',
    level: 'Expert',
    category: 'database',
    hasStar: false,
  },
  {
    name: 'MS SQL Server',
    icon: '/icons/sql_server.svg',
    level: 'Expert',
    category: 'database',
    hasStar: false,
  },
  {
    name: 'Oracle',
    icon: '/icons/oracle.svg',
    level: 'Advanced',
    category: 'database',
    hasStar: false,
  },
  {
    name: 'PostgreSQL',
    icon: '/icons/postgressql.svg',
    level: 'Advanced',
    category: 'database',
    hasStar: false,
  },
  {
    name: 'Redis',
    icon: '/icons/redis.svg',
    level: 'Expert',
    category: 'database',
    hasStar: false,
  },
  // devops
  {
    name: 'AWS',
    icon: '/icons/aws.svg',
    level: 'Expert',
    category: 'devops',
    hasStar: true,
  },
  {
    name: 'GCP',
    icon: '/icons/google_cloud.svg',
    level: 'Advanced',
    category: 'devops',
    hasStar: false,
  },
  {
    name: 'Docker',
    icon: '/icons/docker.svg',
    level: 'Expert',
    category: 'devops',
    hasStar: false,
  },
  {
    name: 'Github',
    icon: '/icons/github.svg',
    level: 'Expert',
    category: 'devops',
    hasStar: false,
  },
  {
    name: 'Gitlab',
    icon: '/icons/gitlab.svg',
    level: 'Expert',
    category: 'devops',
    hasStar: false,
  },
  {
    name: 'Firebase',
    icon: '/icons/firebase.svg',
    level: 'Intermediate',
    category: 'devops',
    hasStar: false,
  },
  // tools
  {
    name: 'VS Code',
    icon: '/icons/vscode.svg',
    level: 'Expert',
    category: 'tools',
    hasStar: false,
  },
  {
    name: 'Git',
    icon: '/icons/git.svg',
    level: 'Expert',
    category: 'tools',
    hasStar: false,
  },
  {
    name: 'OpenAI',
    icon: '/icons/openai.svg',
    level: 'Advanced',
    category: 'tools',
    hasStar: false,
  },
  {
    name: 'Figma',
    icon: '/icons/figma.svg',
    level: 'Intermediate',
    category: 'tools',
    hasStar: false,
  },
];

export const order: Category[] = [
  'backend',
  'frontend',
  'library',
  'database',
  'devops',
  'tools',
];

export const labels: Record<Category, string> = {
  backend: 'Backend',
  frontend: 'Frontend',
  library: 'Libraries',
  database: 'Databases',
  devops: 'Cloud & DevOps',
  tools: 'Tools & Others',
};

export const categories: { key: Category | 'all'; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'backend', label: 'Backend' },
  { key: 'frontend', label: 'Frontend' },
  { key: 'library', label: 'Libraries' },
  { key: 'database', label: 'Databases' },
  { key: 'devops', label: 'DevOps' },
  { key: 'tools', label: 'Tools' },
];
