import type { ExperienceItem } from '@/components/me/experience/experience.types';

export const experiencesSeed: ExperienceItem[] = [
  {
    isOpen: true,
    company: 'Freelance',
    role: 'Full Stack Developer',
    duration: 'Present',
    type: 'Freelance',
    location: 'Remote',
    techStacks: [
      'Laravel',
      'Livewire',
      'Filament',
      'NativePHP',
      'Wordpress',
      'React.js',
      'Typescript',
      'Tailwind CSS',
      'Shadcn UI',
      'Pest',
      'MySQL',
      'Oracle',
      'SQL Server',
      'SQLite',
      'OpenAI',
      'AWS',
    ],
    achievements: [
      'Led development of a microservices architecture serving 1M+ users',
      'Reduced application load time by 40% through performance optimization',
      'Mentored 5 junior developers and established coding standards',
      'Architected and implemented real-time collaboration features',
    ],
  },
  {
    isOpen: true,
    company: 'PT Adi Data Informatika',
    role: 'Lead Developer',
    duration: 'Oct 2022 - Mar 2024',
    type: 'Full Time',
    location: 'Hybrid',
    techStacks: [
      'Laravel',
      'Livewire',
      'Alpine.js',
      'React.js',
      'Typescript',
      'MySQL',
      'SQL Server',
      'AWS',
      'GCP',
    ],
    achievements: [
      'Led development of a microservices architecture serving 1M+ users',
      'Reduced application load time by 40% through performance optimization',
      'Mentored 5 junior developers and established coding standards',
      'Architected and implemented real-time collaboration features',
    ],
  },
  {
    isOpen: false,
    company: 'PT Asemka Commerce Indonesia',
    role: 'Full Stack Developer',
    duration: 'Sep 2017 - Sep 2022',
    type: 'Full Time',
    location: 'On-site',
    techStacks: [
      'Laravel',
      'Livewire',
      'Alpine.js',
      'Vue.js',
      'jQuery',
      'Prestashop',
      'Wordpress',
      'MySQL',
      'SQL Server',
      'AWS',
      'GCP',
    ],
    achievements: [
      'Built MVP from scratch that secured $2M Series A funding',
      'Implemented automated testing pipeline reducing bugs by 60%',
      'Designed and developed RESTful APIs serving 100K+ requests daily',
      'Collaborated with product team to deliver features ahead of schedule',
    ],
  },
  {
    isOpen: false,
    company: 'PT Adicipta Inovasi Teknologi',
    role: 'Full Stack Developer',
    duration: 'Jan 2016 - Aug 2017',
    type: 'Full Time',
    location: 'On-site',
    techStacks: ['CS-Cart', 'Laravel', 'jQuery', 'Bootstrap', 'MySQL'],
    achievements: [
      'Developed responsive web applications for 50+ enterprise clients',
      'Improved code quality by implementing comprehensive testing suite',
      'Created reusable component library used across multiple projects',
      'Optimized bundle size resulting in 25% faster page load times',
    ],
  },
  {
    isOpen: false,
    company: 'CV Kabayan Consulting',
    role: 'Junior Developer',
    duration: 'Jun 2014 - Dec 2014',
    type: 'Internship / Full Time',
    location: 'On-site',
    techStacks: ['Yii', 'Laravel', 'jQuery', 'Bootstrap', 'MySQL'],
    achievements: [
      'Delivered 30+ client websites with pixel-perfect designs',
      'Learned modern development practices and version control',
      'Contributed to cross-browser compatibility and accessibility improvements',
      'Participated in agile development process and client communications',
    ],
  },
];
